# syntax=docker/dockerfile:1

FROM --platform=linux/amd64 ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        git \
        python2 \
        python3-dev \
        python3-pip \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*

ARG NYX_URL=https://github.com/Troublor/Nyx.git
RUN git clone ${NYX_URL} /nyx

WORKDIR /nyx
RUN python3 -m pip install --upgrade pip && pip install -e .

COPY contracts_dataset/dataset_nyx/ /dataset/

COPY run_nyx.sh /usr/local/bin/run_nyx.sh
RUN chmod +x /usr/local/bin/run_nyx.sh

ENTRYPOINT ["/usr/local/bin/run_nyx.sh"]
CMD ["/dataset"]